name: Pull Request
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: testing
        shell: bash
        run: echo ${{ secrets.TESTING_THINGS }}
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml
    secrets: inherit
