name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run-verify:
        type: boolean
        description: 'Run verification after release'
        required: false
        default: false

permissions:
  id-token: write
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: '[Release] Candidate'
          commit: 'chore: bumps package versions'
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  verify:
    needs: release
    if: ${{ inputs.run-verify && needs.release.outputs.pullRequestNumber != '' }}
    uses: ./.github/workflows/verify.yml
    secrets: inherit
    with:
      run-acceptance: true
