name: 'Verify'
on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.0.6

      - name: Run Biome
        run: biome ci .

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        uses: ./.github/actions/tests
        with:
          environment: 'staging'
          private_key: ${{ secrets.PRIVATE_KEY }}
