name: 'Verify'
on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.0.6

      - name: Run Biome
        run: biome ci .

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Setup Repository
        uses: ./.github/actions/setup

      - name: Build
        shell: bash
        run: pnpm build

      - name: Setup Environment Variables
        shell: bash
        run: |
          echo "ENVIRONMENT=${{ inputs.environment }}" >> .env

      - name: Run Tests
        shell: bash
        run: pnpm test
