name: 'Verify'
on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.0.6

      - name: Run Biome
        run: biome ci .

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      ENVIRONMENT: staging
      PRIVY_TEST_APP_ID: ${{ vars.PRIVY_TEST_APP_ID }}
      PRIVY_TEST_APP_SECRET: ${{ secrets.PRIVY_TEST_APP_SECRET }}
      PRIVY_TEST_WALLET_ID: ${{ vars.PRIVY_TEST_WALLET_ID }}
      PRIVY_TEST_WALLET_ADDRESS: ${{ vars.PRIVY_TEST_WALLET_ADDRESS }}

    steps:
      - name: Setup Repository
        uses: ./.github/actions/setup

      - name: Build
        shell: bash
        run: pnpm build

      - name: Run Tests
        shell: bash
        run: pnpm test
